# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(600, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 300))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_download = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_download.setGeometry(QtCore.QRect(410, 180, 141, 61))
        self.pushButton_download.setObjectName("pushButton_download")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 100, 69, 25))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 130, 69, 26))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_titulo.setGeometry(QtCore.QRect(70, 130, 469, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_titulo.setFont(font)
        self.lineEdit_titulo.setObjectName("lineEdit_titulo")
        self.lineEdit_link = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_link.setGeometry(QtCore.QRect(70, 100, 469, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_link.setFont(font)
        self.lineEdit_link.setObjectName("lineEdit_link")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 20, 281, 41))
        self.label_4.setObjectName("label_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 180, 101, 61))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_mp3 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_mp3.setObjectName("radioButton_mp3")
        self.verticalLayout.addWidget(self.radioButton_mp3)
        self.radioButton_mp4 = QtWidgets.QRadioButton(self.widget)
        self.radioButton_mp4.setObjectName("radioButton_mp4")
        self.verticalLayout.addWidget(self.radioButton_mp4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_link, self.lineEdit_titulo)
        MainWindow.setTabOrder(self.lineEdit_titulo, self.radioButton_mp3)
        MainWindow.setTabOrder(self.radioButton_mp3, self.radioButton_mp4)
        MainWindow.setTabOrder(self.radioButton_mp4, self.pushButton_download)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_download.setText(_translate("MainWindow", "Download"))
        self.label.setText(_translate("MainWindow", "Link :"))
        self.label_2.setText(_translate("MainWindow", "Título :"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/img_youtube/youtube.png\"/><span style=\" font-size:18pt; font-weight:600; font-style:italic;\">YouTube Download</span></p></body></html>"))
        self.radioButton_mp3.setText(_translate("MainWindow", "MP3"))
        self.radioButton_mp4.setText(_translate("MainWindow", "MP4"))
import youtube


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
